import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "@/provider/Provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html style={{ colorScheme: "light" }}>
      <body className="bg-gray-100/10 dark:bg-zinc-900/50 transition-all ease-out duration-700">
        <Providers>
          <Header />
          <div className="mx-auto max-w-7xl ">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
